[general]
domain_id = "domain-1"
orchestrator_url = "http://127.0.0.1:7011"
orchestrator_url_announced = ""
orchestrator_coap_url = "coap://127.0.0.1:7050"
orchestrator_coap_url_announced = ""
agent_url = "http://127.0.0.1:7121"
agent_url_announced = ""
invocation_url = "http://127.0.0.1:7102"
invocation_url_announced = ""

[baseline]
orchestration_strategy = "Random"
keep_alive_interval_secs = 2

[proxy]
proxy_type = "None"
redis_url = ""

[proxy.dataset_settings]
dataset_path = ""
append = true
additional_fields = ""
additional_header = ""

[collector]
collector_type = "None"
redis_url = ""
