
services:
   edgeless_docker:
      tty: true
      image: edgeless_v0.5.1
      container_name: edgeless_container
      network_mode: host
      privileged: true
      volumes: 
        - /tmp/.X11-unix:/tmp/.X11-unix:rw
        - ~/.xauth_docker/share/:/tmp/xauth/
        - /dev/input:/dev/input
        - /dev/bus/usb:/dev/bus/usb
        - ../:/home/user/dev/:rw 
        - ./scripts:/scripts
      environment:
        - DISPLAY=$DISPLAY
        - QT_X11_NO_MITSHM=1
        - XAUTHORITY=/tmp/xauth/.docker.xauth     
      working_dir: /home/user/dev
      devices:
        - /dev/dri:/dev/dri
        - /dev/snd:/dev/snd
        - /dev/bus/usb:/dev/bus/usb:rw
      user: "user:user"
      command: ["/bin/bash", "-c", "chmod +x /scripts/setup_bashrc.sh && /scripts/setup_bashrc.sh && bash"]

